[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date in the migration file
# as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a
# standalone script, rather than emitting the string
# run it
# standalone_mode = false

# enable logging file rotation.
# max bytes for each log file
# logging_file_max_bytes = 100000

# number of log files to keep
# logging_file_max_count = 3

# 'logging_config_file' - path to .ini file, relative to this
# directory
# The string value below points to file in the Alembic project
# directory that should be present
# Cambia esto en tu alembic.ini
logging_config_file = alembic.ini

# set to 'true' to use colors to format the status output
# console_command = false

# If set to true, "alembic current" will show the revision hash
# in addition to the revision number.  Defaults to False.
# revision_environment = false

# set the URL to the database
# sqlAlchemy.url = postgresql://scanops:scanops@localhost:5432/scanops

# set to 'true' to have the command otherwise printed
# echo = true

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# format using "black" - use the console_command setting above if using the -c option
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S