%YAML 1.1
---

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"
    DC_SERVERS: "$HOME_NET"

  port-groups:
    HTTP_PORTS: "80"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: 1521
    SSH_PORTS: 22
    FTP_PORTS: 21
    FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"

af-packet:
  - interface: default

pcap:
  - interface: lo
    checksum-checks: auto

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      community-id: true
      types:
        - alert:
            payload: yes
            payload-printable: yes
            metadata: yes
        - anomaly:
            enabled: yes
        - http:
            extended: yes
        - dns:
            query: yes
            answer: yes
        - tls:
            extended: yes
        - flow: {}

  - stats:
      enabled: yes
      filename: /var/log/suricata/stats.log
      totals: yes
      threads: no
      null-values: yes

logging:
  default-log-level: notice
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log

app-layer:
  protocols:
    tls:
      enabled: yes
      detection-ports:
        dp: 443
    http:
      enabled: yes
    ftp:
      enabled: yes
    ssh:
      enabled: yes
    dns:
      enabled: yes
    modbus:
      enabled: no
      detection-enabled: no
    dnp3:
      enabled: no
    enip:
      enabled: no

default-rule-path: /var/lib/suricata/rules

rule-files:
  - suricata.rules
  - /etc/suricata/scanops.rules

stats:
  enabled: yes
  interval: 8

max-pending-packets: 1024

defrag:
  memcap: 64mb
  hash-size: 65536
  trackers: 65535
  max-frags: 65535
  prealloc: yes
  timeout: 60

flow:
  memcap: 128mb
  hash-size: 65536
  prealloc: 10000
  emergency-recovery: 30

host:
  hash-size: 4096
  prealloc: 1000
  memcap: 32mb

detect:
  profile: medium
  sgh-mpm-context: auto
  inspection-recursion-limit: 3000

unix-command:
  enabled: auto
  filename: /var/run/suricata/suricata-command.socket
